### ISSUE TITLE
Temperature Converter

### ISSUE THREAD

**Issue by MXNXV** [Developer-Students-Clubs-MESCOE/HacktoberFest_2021_Utility_Apps#4]
Add a temperature converter to convert from these units:

- Celsius
- Kelvin
- Fahrenheit

**Comment by ganeshkalyank** [comment]
Can I work on this?

**Comment by ganeshkalyank** [comment]
#5 Check this pull request

**Comment by sumitbarmecha** [comment]
can you assign me this issue!!

**Comment by AayushBiswas** [comment]
Can you assign this issue to me

**Comment by ganeshkalyank** [comment]
Could you please label my PR **hacktoberfest-accepted**.
